---

- name: ensure old versions of docker are not installed
  package:
    name: 'remove'
    state: absent
  with_items:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-selinux
    - docker-engine-selinux
    - docker-engine
    - docker-ce
    - docker-ce-cli

- name: add docker gpg key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: add docker repository
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    owner: root
    group: root
    mode: 0644

- name: install yum-utils
  yum: name=yum-utils state=present

- name: install device-mapper-persistent-data
  yum: name=device-mapper-persistent-data state=present

- name: install lvm2
  yum: name=lvm2 state=present

- name: install docker-ce
  yum: name=docker-ce-18.06.1.ce state=present

- name: enable/start docker service
  service:
    name: docker
    enabled: yes
    state: started

- name: install compose
  include: compose.yml

#- name: install python-pip
#  yum: name=python-pip state=present

#- name: install docker-py
#  shell: pip install 'docker-py>=1.7.0'
