---

- name: Ensure old versions of Docker are not installed.
  package:
    name: 'remove'
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine

- name: Add Docker GPG key.
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository.
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    owner: root
    group: root
    mode: 0644

- name: install docker
  yum: name=docker state=present

- name: enable start docker service
  service:
    name: docker
    enabled: yes
    state: started

- name: install python-pip
  yum: name=python-pip state=present

- name: install docker-py
  shell: pip install 'docker-py>=1.7.0'
